server:
  port: 8080

spring:
  application:
    name: webtrak

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # Hibernate ddl auto (create, create-drop, validate, update)
    # Change hibernate.ddl-auto value to validate when flyway is being used.
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${DATABASE_SCHEMA:public}
        jdbc:
          lob:
            non_contextual_creation: true
#  flyway:
#    schemas: ${DATABASE_SCHEMA:public}
#    baseline-on-migrate: true

# Service configuration / env
template-service:
  environment: ${ENVIRONMENT:dev}
