server:
  port: 8080

webtrak:
  adminPassword: moo$aidTheC0W

spring:
  application:
    name: webtrak

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # Hibernate ddl auto (create, create-drop, validate, update)
    # Change hibernate.ddl-auto value to validate when flyway is being used.
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true
#  flyway:
#    schemas: ${DATABASE_SCHEMA:public}
#    baseline-on-migrate: true

# Service configuration / env
template-service:
  environment: ${ENVIRONMENT:dev}
